language: python
python:
  - 2.7_with_system_site_packages
sudo: false
addons:
  apt:
    packages:
    - python-all
    - rubygems
install:
  - gem install package_cloud
  - pip install stdeb
script:
  - tools/makedeb.sh
after_success:
  if ([ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ]) && 
      [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    package_cloud push emersion/bups/elementaryos/freya deb_dist/python-bups_*_all.deb
  fi
