language: python
python:
  - 2.7_with_system_site_packages
sudo: false
addons:
  apt:
    packages:
    - python-all
    - rubygems
install:
  - gem install package_cloud
  - pip install stdeb
script:
  - tools/makedeb.sh
  - package_cloud push emersion/bups/elementaryos/freya deb_dist/python-bups_*_all.deb
